name: Deploy

on:
  push:
    paths:
      - '**.gmi'
      - '**.html'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Convert *.gmi to *.html
        run: |
          mkdir -p ./pub/htm
          curl -sO https://notabug.org/tinyrabbit/gmi2html/raw/master/gmi2html
          chmod +x gmi2html
          find pub/gmi/* -type d | sed 's_/gmi/_/htm/_' | xargs mkdir -p
          find -name "*.gmi" -type f | while read -r i; do
            o="$(echo "${i/\.gmi/.html}" | sed 's_/gmi/_/htm/_')"
            echo "$i->$o"
            ./gmi2html "$i" > "$o"
          done
          rm gmi2html ./pub/gmi/.gitkeep ./pub/htm/.gitkeep
      - name: Check
        run: find pub -type f
      - name: Archive html + gmi files into tar
        run: |
          cd ./pub/htm
          tar -czf ./../../htm.tar.gz .
          cd ./../gmi
          tar -cvf ./../../gmi.tar.gz .
          cd ./../../
      - name: Upload files
        run: |
          SH_USER=eggplants
          curl -s --oauth2-bearer "${{ secrets.SH_TOKEN }}" \
               -F "content=@htm.tar.gz" \
               "https://pages.sr.ht/publish/${SH_USER}.srht.site" \
          && echo "published: https://${SH_USER}.srht.site"
          curl -s --oauth2-bearer "${{ secrets.SH_TOKEN }}" \
               -Fcontent=@gmi.tar.gz \
               -Fprotocol=GEMINI \
               https://pages.sr.ht/publish/${SH_USER}.srht.site \
          && echo "published: gemini://${SH_USER}.srht.site"
